//
//  Enums.swift
//  CoinMarket
//
//  Created by Oksana Dionisieva on 16.04.2022.
//

import Foundation

enum Name: String, Codable {
    case algorand = "Algorand"
    case arbitrum = "Arbitrum"
    case aurora = "Aurora"
    case avalancheCChain = "Avalanche C-Chain"
    case avalancheDFK = "Avalanche DFK"
    case bitcoinCash = "Bitcoin Cash"
    case bnbBeaconChainBEP2 = "BNB Beacon Chain (BEP2)"
    case bnbSmartChainBEP20 = "BNB Smart Chain (BEP20)"
    case bobaNetwork = "Boba Network"
    case cardano = "Cardano"
    case celo = "Celo"
    case chiliz = "Chiliz"
    case cosmos = "Cosmos"
    case cronos = "Cronos"
    case elastos = "Elastos"
    case elrond = "Elrond"
    case eos = "EOS"
    case ethereum = "Ethereum"
    case fantom = "Fantom"
    case fuse = "Fuse"
    case harmony = "Harmony"
    case heco = "HECO"
    case hooSmartChain = "Hoo Smart Chain"
    case htmlcoin = "HTMLCOIN"
    case ioTex = "IoTex"
    case iost = "IOST"
    case kardiaChain = "KardiaChain"
    case kcc = "KCC"
    case klaytn = "Klaytn"
    case kusama = "Kusama"
    case metisAndromeda = "Metis Andromeda"
    case milkomeda = "Milkomeda"
    case moonbeam = "Moonbeam"
    case moonriver = "Moonriver"
    case neo = "Neo"
    case oasisNetwork = "Oasis Network"
    case okExChain = "OKExChain"
    case ont = "ONT"
    case optimism = "Optimism"
    case polygon = "Polygon"
    case rskRbtc = "RSK RBTC"
    case secret = "Secret"
    case solana = "Solana"
    case songbirdNetwork = "Songbird Network"
    case stellar = "Stellar"
    case telos = "Telos"
    case terra = "Terra"
    case tezos = "Tezos"
    case tomoChain = "TomoChain"
    case tron10 = "Tron10"
    case tron20 = "Tron20"
    case veChain = "VeChain"
    case velas = "Velas"
    case wanchain = "Wanchain"
    case waves = "Waves"
    case xDai = "xDai"
    case xinfinNetworkXDC = "Xinfin Network (XDC)"
    case xrpLedger = "XRP Ledger"
    case zilliqa = "Zilliqa"
}

enum Symbol: String, Codable {
    case ada = "ADA"
    case algo = "ALGO"
    case arbitrum = "ARBITRUM"
    case atom = "ATOM"
    case aurora = "AURORA"
    case avax = "AVAX"
    case bch = "BCH"
    case bnb = "BNB"
    case boba = "BOBA"
    case celo = "CELO"
    case chz = "CHZ"
    case cro = "CRO"
    case egld = "EGLD"
    case ela = "ELA"
    case eos = "EOS"
    case eth = "ETH"
    case ftm = "FTM"
    case fuse = "FUSE"
    case glmr = "GLMR"
    case hsc = "HSC"
    case ht = "HT"
    case html = "HTML"
    case iost = "IOST"
    case iotx = "IOTX"
    case kai = "KAI"
    case kcs = "KCS"
    case klay = "KLAY"
    case ksm = "KSM"
    case luna = "LUNA"
    case matic = "MATIC"
    case metis = "METIS"
    case movr = "MOVR"
    case neo = "NEO"
    case okt = "OKT"
    case one = "ONE"
    case ont = "ONT"
    case rbtc = "RBTC"
    case rose = "ROSE"
    case scrt = "SCRT"
    case sgb = "SGB"
    case sol = "SOL"
    case stake = "STAKE"
    case tlos = "TLOS"
    case tomo = "TOMO"
    case trx = "TRX"
    case vet = "VET"
    case vlx = "VLX"
    case wan = "WAN"
    case waves = "WAVES"
    case xdc = "XDC"
    case xlm = "XLM"
    case xrp = "XRP"
    case xtz = "XTZ"
    case zil = "ZIL"
}
